### ISSUE TITLE
running application in precompiled mode throws ClassNotFoundException

### ISSUE THREAD

**Issue by braman** [marcuspocus/hazelcast#14]
After deploying into production environment and running the precompile  command the application starts fine, but when I start sending messages into topics it says:

WARNING: [10.0.0.167]:5799 [prod] [3.7.1] Error while logging processing event
com.hazelcast.nio.serialization.HazelcastSerializationException: java.lang.ClassNotFoundException: pojo.system.events.StatusChangedEvent
    at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:224)
    at com.hazelcast.internal.serialization.impl.StreamSerializerAdapter.read(StreamSerializerAdapter.java:46)
    at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:172)
    at com.hazelcast.topic.impl.DataAwareMessage.getMessageObject(DataAwareMessage.java:44)
    at jobs.StartupJob$1.onMessage(StartupJob.java:72)
    at com.hazelcast.topic.impl.TopicService.dispatchEvent(TopicService.java:134)
    at com.hazelcast.spi.impl.eventservice.impl.EventProcessor.process(EventProcessor.java:48)
    at com.hazelcast.spi.impl.eventservice.impl.RemoteEventProcessor.run(RemoteEventProcessor.java:36)
    at com.hazelcast.util.executor.StripedExecutor$Worker.process(StripedExecutor.java:187)
    at com.hazelcast.util.executor.StripedExecutor$Worker.run(StripedExecutor.java:171)
Caused by: java.lang.ClassNotFoundException: pojo.system.events.StatusChangedEvent
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.hazelcast.nio.ClassLoaderUtil.tryLoadClass(ClassLoaderUtil.java:151)
    at com.hazelcast.nio.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:120)
    at com.hazelcast.nio.IOUtil$ClassLoaderAwareObjectInputStream.resolveClass(IOUtil.java:358)
    at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
    at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    at com.hazelcast.internal.serialization.impl.JavaDefaultSerializers$JavaSerializer.read(JavaDefaultSerializers.java:219)
    ... 9 more

**Comment by braman** [comment]
Fixed by #15
